### ISSUE TITLE
Cannot load file

### ISSUE THREAD

**Issue by jerryandtom007** [JoGaTo/nyaa.si-batch-uploader#6]
It can't load files anymore, I don't know if there is hope to fix it.

**Comment by JoGaTo** [comment]
The download link or the actual files?

**Comment by jerryandtom007** [comment]
> 下载链接还是实际文件？

**Comment by jerryandtom007** [comment]
问题已经修复了，谢谢！

**Comment by JoGaTo** [comment]
Fixed how? I tested this out yesterday and wouldn't load a test file.
